# Các bước sử dụng code Deep learning

## Bước 1: Tìm file requirements.txt

### Cài đặt môi trường python

- virtual environment: vitualenv
- conda environment

### Cài đặt thư viện

``` python
pip intall -r requirements.txt
```

## Bước 2: Tìm file dùng để predict

- predict.py
- infer.py
- inference.py
- demo.py
- detect.py
- ...

## Bước 3: Tìm file model checkpoint

## Bước 4: Chạy predict và xem kết quả

## Bước 5: Tìm file dùng để train

- train.py
- train_abcxyz.py

## Bước 6: (RẤT QUAN TRỌNG) Chuẩn bị dữ liệu phù hợp để train

Phù hợp nghĩa là cấu trúc thư mục giống với tác giả yêu cầu

## Bước 7: Chạy train mô hình

In [1]:
!ls ../0_public_repositories/datasets/coco

LICENSE          images           train2017.cache  val2017.txt
README.txt       labels           train2017.txt
annotations      test-dev2017.txt val2017.cache

In [2]:
!ls ../0_public_repositories/datasets/coco/images

test2017  train2017 val2017

In [3]:
!ls ../0_public_repositories/datasets/coco/labels

train2017 val2017

In [4]:
!mkdir brain_tumor_coco
!mkdir brain_tumor_coco/images
!mkdir brain_tumor_coco/images/train
!mkdir brain_tumor_coco/images/val
!mkdir brain_tumor_coco/images/test
!mkdir brain_tumor_coco/labels
!mkdir brain_tumor_coco/labels/train
!mkdir brain_tumor_coco/labels/val

In [5]:
!ls brain_tumor_coco/

images labels

In [6]:
!ls brain_tumor_coco/images

test  train val

In [7]:
!ls brain_tumor_coco/labels

train val

In [8]:
!cp brain_tumor_dataset/test/* brain_tumor_coco/images/test

# 1. Chuẩn bị dữ liệu ảnh

In [9]:
import pandas as pd
from tqdm import tqdm
from PIL import Image

from glob import glob
import json
import os

In [10]:
df = pd.read_csv('brain_tumor_dataset/brain_multi.csv')
df = df.sample(frac=1)

In [11]:
train_df = df.iloc[:4000]
train_df

,image_name,label,x1,y1,x2,y2,conf
4826,Cancer-958-_jpg.rf.2831000c5adc22bb1e7b4a1a606...,tumor,401,224,573,336,0.767296
1347,Not-Cancer-1887-_jpg.rf.460b3297ffe65380ec750a...,normal,0,0,640,640,0.119376
1453,y398_jpg.rf.16b3d18521f18a09f3af0aac7e8ca92f.jpg,tumor,188,238,323,341,0.093145
2615,Cancer-319-_jpg.rf.12160c95520ab9b11e65a7febdf...,tumor,389,277,494,366,0.846501
4926,y363_jpg.rf.b9b54bf1ac9956fa52f5ea3d4da5f2a0.jpg,tumor,271,122,390,262,0.375621
...,...,...,...,...,...,...,...
5801,Cancer-1928-_jpg.rf.302aa4de413da7c7f26edcdd14...,tumor,429,139,585,258,0.194574
4726,Cancer-1971-_jpg.rf.fa0cc4bfc859683e8abff1682b...,tumor,313,124,449,200,0.146616
248,Cancer-180-_jpg.rf.cfd2149ec3c7d9614bc93717af8...,tumor,433,215,505,282,0.061537
3385,Cancer-876-_jpg.rf.3ab3370b7d91c93f4481f075fbe...,tumor,446,361,536,469,0.956418
3843,y160_jpg.rf.7138a69dc4ca5aacaf960374c1c49af4.jpg,tumor,249,206,457,361,0.739854

In [12]:
val_df = df.iloc[4000:]
val_df

,image_name,label,x1,y1,x2,y2,conf
3315,Not-Cancer-1386-_jpg.rf.d688ad8eed3a5acd2675c2...,normal,0,0,640,640,0.007350
5845,Not-Cancer-306-_jpg.rf.3a9152e112e4a94837d9442...,normal,0,0,640,640,0.693618
313,Cancer-1446-_jpg.rf.622889c31f560feae9bc225fc5...,tumor,335,173,512,356,0.083072
1976,y267_jpg.rf.9d362dd6e083492a78c3815ddd4e560a.jpg,tumor,72,210,238,380,0.583525
2965,y311_jpg.rf.7973f7798bf2b7ec0a059291e8f52f52.jpg,tumor,284,369,499,569,0.694959
...,...,...,...,...,...,...,...
5178,y289_jpg.rf.065ffaaa43e5744240005d2707aaf8b9.jpg,tumor,443,142,584,262,0.825195
4100,y266_jpg.rf.ef4f2aa789918b5d3ea4e5801fb2a4c6.jpg,tumor,373,81,565,312,0.962321
4141,Cancer-1038-_JPG.rf.0e2e29a9263f466cb4438f1927...,tumor,406,308,561,472,0.659088
1987,Not-Cancer-1466-_jpg.rf.eae1823940bafdf379ed59...,normal,0,0,640,640,0.299092
246,Cancer-32-_jpg.rf.0d8c77153f6a000bef3a93d25971...,tumor,275,333,356,408,0.343307

In [13]:
for image_name in tqdm(train_df.image_name.to_list()):
    os.system(f'cp brain_tumor_dataset/train/{image_name} brain_tumor_coco/images/train/')

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:37<00:00, 107.63it/s]

In [14]:
for image_name in tqdm(val_df.image_name.to_list()):
    os.system(f'cp brain_tumor_dataset/train/{image_name} brain_tumor_coco/images/val/')

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1870/1870 [00:16<00:00, 110.88it/s]

# 2. Chuẩn bị label

In [15]:
train_df[['image_name', 'label', 'x1', 'y1', 'x2', 'y2']]

,image_name,label,x1,y1,x2,y2
4826,Cancer-958-_jpg.rf.2831000c5adc22bb1e7b4a1a606...,tumor,401,224,573,336
1347,Not-Cancer-1887-_jpg.rf.460b3297ffe65380ec750a...,normal,0,0,640,640
1453,y398_jpg.rf.16b3d18521f18a09f3af0aac7e8ca92f.jpg,tumor,188,238,323,341
2615,Cancer-319-_jpg.rf.12160c95520ab9b11e65a7febdf...,tumor,389,277,494,366
4926,y363_jpg.rf.b9b54bf1ac9956fa52f5ea3d4da5f2a0.jpg,tumor,271,122,390,262
...,...,...,...,...,...,...
5801,Cancer-1928-_jpg.rf.302aa4de413da7c7f26edcdd14...,tumor,429,139,585,258
4726,Cancer-1971-_jpg.rf.fa0cc4bfc859683e8abff1682b...,tumor,313,124,449,200
248,Cancer-180-_jpg.rf.cfd2149ec3c7d9614bc93717af8...,tumor,433,215,505,282
3385,Cancer-876-_jpg.rf.3ab3370b7d91c93f4481f075fbe...,tumor,446,361,536,469
3843,y160_jpg.rf.7138a69dc4ca5aacaf960374c1c49af4.jpg,tumor,249,206,457,361

In [16]:
with open('../0_public_repositories/datasets/coco/labels/val2017/000000000139.txt', 'r') as file:
    lines = file.readlines()

# Format: object_index - x_center - y_center - width - height
lines

['58 0.389578 0.416103 0.0385937 0.163146\n',
 '62 0.127641 0.505153 0.233312 0.2227\n',
 '62 0.934195 0.583462 0.127109 0.184812\n',
 '56 0.604656 0.632547 0.0875 0.241385\n',
 '56 0.502508 0.627324 0.0966094 0.231174\n',
 '56 0.669195 0.618991 0.0471406 0.190986\n',
 '56 0.512797 0.528251 0.0337187 0.0272066\n',
 '0 0.686445 0.53196 0.0828906 0.323967\n',
 '0 0.612484 0.446197 0.023625 0.0838967\n',
 '68 0.811859 0.501725 0.0230312 0.0374883\n',
 '72 0.78632 0.536373 0.0317031 0.254249\n',
 '73 0.956156 0.771702 0.0224062 0.1073\n',
 '73 0.96825 0.778075 0.020125 0.109014\n',
 '74 0.710555 0.31 0.0218281 0.0513615\n',
 '75 0.886562 0.831608 0.0573125 0.210493\n',
 '75 0.556945 0.516702 0.0177656 0.0529343\n',
 '56 0.651664 0.528826 0.0150469 0.0293897\n',
 '75 0.388047 0.478415 0.0222188 0.041385\n',
 '75 0.533836 0.487946 0.0152031 0.0392723\n',
 '60 0.599984 0.647148 0.196188 0.208756\n']

In [17]:
def prepare_label_txt(image_name, label, x1, y1, x2, y2, dataset_name):
    img = Image.open(f'brain_tumor_dataset/train/{image_name}')
    img_w, img_h = img.size[0], img.size[1]
    # Convert from Absolute bounding box to Relative bounding box
    x = (x1 + x2) / 2 / img_w
    y = (y1 + y2) / 2 / img_h
    w = (x2 - x1) / img_w
    h = (y2 - y1) / img_h
    image_name = image_name.replace('.jpg', '.txt')
    with open(f'brain_tumor_coco/labels/{dataset_name}/{image_name}', 'w') as file:
        if label == 'tumor':
            file.write(f'0 {x} {y} {w} {h}')
        else:
            pass

In [18]:
for _, row in tqdm(train_df.iterrows()):
    prepare_label_txt(
        row.image_name, row.label, row.x1, row.y1, row.x2, row.y2, 'train'
    )

4000it [00:02, 1605.99it/s]

In [19]:
for _, row in tqdm(val_df.iterrows()):
    prepare_label_txt(
        row.image_name, row.label, row.x1, row.y1, row.x2, row.y2, 'val'
    )

1870it [00:01, 1527.72it/s]

In [20]:
sample_name = os.listdir('./brain_tumor_coco/labels/val/')[0]
with open(f'./brain_tumor_coco/labels/val/{sample_name}', 'r') as file:
    lines = file.readlines()
lines

['0 0.49453125 0.4703125 0.2015625 0.215625']

# 3. Chuẩn bị file txt đường dẫn

In [21]:
def create_txt_path_file(root_path, dataset_name):
    file_path_list = glob(os.path.join(root_path, dataset_name, '*'))
    file_path_list = [path.replace('brain_tumor_coco', '.') + '\n' for path in file_path_list]
    with open(f'brain_tumor_coco/{dataset_name}.txt', 'w') as file:
        file.writelines(file_path_list)

In [22]:
create_txt_path_file('brain_tumor_coco/images/', 'val')

In [23]:
create_txt_path_file('brain_tumor_coco/images/', 'train')

In [24]:
create_txt_path_file('brain_tumor_coco/images/', 'test')

In [25]:
with open('../0_public_repositories/datasets/coco/val2017.txt', 'r') as file:
    lines = file.readlines()
lines[:10]

['./images/val2017/000000182611.jpg\n',
 './images/val2017/000000335177.jpg\n',
 './images/val2017/000000278705.jpg\n',
 './images/val2017/000000463618.jpg\n',
 './images/val2017/000000568981.jpg\n',
 './images/val2017/000000092416.jpg\n',
 './images/val2017/000000173830.jpg\n',
 './images/val2017/000000476215.jpg\n',
 './images/val2017/000000479126.jpg\n',
 './images/val2017/000000570664.jpg\n']

In [26]:
with open('brain_tumor_coco/val.txt', 'r') as file:
    lines = file.readlines()
lines[:10]

['./images/val/Not-Cancer-205-_jpg.rf.516a86e9b123d5e12000fe32483d2d26.jpg\n',
 './images/val/y407_jpg.rf.1bd00e8baf5d468619b53f41b2a9c186.jpg\n',
 './images/val/Not-Cancer-2026-_jpg.rf.65887d21d01b016586e9d361be85f005.jpg\n',
 './images/val/y34_jpg.rf.ee643f5812fab37b60592746dac3ae10.jpg\n',
 './images/val/Cancer-1585-_jpg.rf.4b135d6aa1e41b4879a775cc4da55ae9.jpg\n',
 './images/val/Cancer-835-_jpg.rf.3a3318e66898956b512becac2e3d82e0.jpg\n',
 './images/val/y381_jpg.rf.41a5a22ec00c92f4d604b6634b73a07c.jpg\n',
 './images/val/Not-Cancer-1180-_jpg.rf.62698fbc9bb6aee7f6fd027255e9c972.jpg\n',
 './images/val/Cancer-1348-_jpg.rf.34af6573fd9c0e084d5002147d54cf90.jpg\n',
 './images/val/y458_jpg.rf.42177de6c98322cf75f752fbe9244770.jpg\n']